"""estrutura inicial

Revision ID: d7ec8a58b23d
Revises: 
Create Date: 2026-10-06 22:19:29.227862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7ec8a58b23d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cd_centros',
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('cr_norm', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=200), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('origem_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_id')
    )
    with op.batch_alter_table('cd_centros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cd_centros_cr_norm'), ['cr_norm'], unique=False)

    op.create_table('cd_despesas',
    sa.Column('centro_origem_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_origem_id', sa.Integer(), nullable=False),
    sa.Column('natureza_origem_id', sa.Integer(), nullable=False),
    sa.Column('data_baixa', sa.Date(), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('valor_original', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_baixado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('referencia', sa.Integer(), nullable=True),
    sa.Column('documento', sa.String(length=30), server_default='', nullable=False),
    sa.Column('historico', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('origem_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_id')
    )
    with op.batch_alter_table('cd_despesas', schema=None) as batch_op:
        batch_op.create_index('ix_cd_despesas_centro_data', ['centro_origem_id', 'data_baixa'], unique=False)
        batch_op.create_index('ix_cd_despesas_centro_natureza_data', ['centro_origem_id', 'natureza_origem_id', 'data_baixa'], unique=False)

    op.create_table('cd_fornecedores',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('origem_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_id')
    )
    op.create_table('cd_naturezas',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nome_norm', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('origem_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_id')
    )
    with op.batch_alter_table('cd_naturezas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cd_naturezas_nome_norm'), ['nome_norm'], unique=False)

    op.create_table('rc_ajustes',
    sa.Column('contrato_origem_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('valor_anterior', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_novo', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_anterior', sa.Date(), nullable=True),
    sa.Column('data_nova', sa.Date(), nullable=True),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('criado_origem_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('origem_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_id')
    )
    with op.batch_alter_table('rc_ajustes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rc_ajustes_contrato_origem_id'), ['contrato_origem_id'], unique=False)

    op.create_table('rc_clientes',
    sa.Column('nome', sa.String(length=200), server_default='', nullable=False),
    sa.Column('nome_completo', sa.String(length=300), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('origem_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_id')
    )
    op.create_table('rc_contrato_coordenadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_origem_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('nome_norm', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_origem_id', 'nome_norm')
    )
    with op.batch_alter_table('rc_contrato_coordenadores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rc_contrato_coordenadores_contrato_origem_id'), ['contrato_origem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rc_contrato_coordenadores_nome_norm'), ['nome_norm'], unique=False)

    op.create_table('rc_contratos',
    sa.Column('cr_code', sa.String(length=40), nullable=False),
    sa.Column('cr_norm', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.String(length=300), server_default='', nullable=False),
    sa.Column('numero_contrato', sa.String(length=100), nullable=True),
    sa.Column('coordenador', sa.String(length=300), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('cliente_origem_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('participacao', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('origem_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_id')
    )
    with op.batch_alter_table('rc_contratos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rc_contratos_cliente_origem_id'), ['cliente_origem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rc_contratos_cr_norm'), ['cr_norm'], unique=False)

    op.create_table('rc_nfs',
    sa.Column('contrato_origem_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('cliente_nome', sa.String(length=300), server_default='', nullable=False),
    sa.Column('emitida_em', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), server_default='principal', nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('origem_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_id')
    )
    with op.batch_alter_table('rc_nfs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rc_nfs_contrato_origem_id'), ['contrato_origem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rc_nfs_emitida_em'), ['emitida_em'], unique=False)

    op.create_table('rc_previsoes',
    sa.Column('contrato_origem_id', sa.Integer(), nullable=False),
    sa.Column('competencia', sa.Date(), nullable=True),
    sa.Column('valor_previsto', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('origem_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_id')
    )
    with op.batch_alter_table('rc_previsoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rc_previsoes_contrato_origem_id'), ['contrato_origem_id'], unique=False)

    op.create_table('rc_recebimentos',
    sa.Column('nf_origem_id', sa.Integer(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('origem_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_id')
    )
    with op.batch_alter_table('rc_recebimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rc_recebimentos_nf_origem_id'), ['nf_origem_id'], unique=False)

    op.create_table('sync_marcas',
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('recurso', sa.String(length=40), nullable=False),
    sa.Column('marca_dados', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marca_exclusoes', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultima_completa_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('fonte', 'recurso')
    )
    op.create_table('tb_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('perfil', sa.String(length=20), server_default='leitor', nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("perfil IN ('leitor', 'operador', 'admin')", name='ck_usuario_perfil'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_tb_usuarios_external_id'), ['external_id'], unique=True)

    op.create_table('cfg_bms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nf_origem_id', sa.Integer(), nullable=False),
    sa.Column('cr_norm', sa.String(length=40), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('data_base', sa.Date(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['tb_usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nf_origem_id')
    )
    with op.batch_alter_table('cfg_bms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cfg_bms_cr_norm'), ['cr_norm'], unique=False)

    op.create_table('cfg_contratos',
    sa.Column('cr_norm', sa.String(length=40), nullable=False),
    sa.Column('fim_execucao', sa.Date(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['tb_usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('cr_norm')
    )
    op.create_table('cfg_depara',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_norm', sa.String(length=40), nullable=False),
    sa.Column('natureza_nome_norm', sa.String(length=200), nullable=False),
    sa.Column('item_codigo', sa.String(length=20), server_default='', nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['tb_usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cr_norm', 'natureza_nome_norm')
    )
    with op.batch_alter_table('cfg_depara', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cfg_depara_cr_norm'), ['cr_norm'], unique=False)

    op.create_table('cfg_importacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('contagens', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('avisos', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cfg_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_norm', sa.String(length=40), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('unidade', sa.String(length=20), server_default='', nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('custo_alvo', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('custo_alvo_projetado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('quantidade_medida', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ordem', sa.Integer(), server_default='0', nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('custo_alvo >= 0', name='ck_item_custo_alvo'),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['tb_usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cr_norm', 'codigo')
    )
    with op.batch_alter_table('cfg_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cfg_itens_cr_norm'), ['cr_norm'], unique=False)

    op.create_table('cfg_parametros',
    sa.Column('cr_norm', sa.String(length=40), nullable=False),
    sa.Column('tributos', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('taxa_adm', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['tb_usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('cr_norm')
    )
    op.create_table('cfg_pendencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_norm', sa.String(length=40), nullable=False),
    sa.Column('assunto', sa.Text(), nullable=False),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('prioridade', sa.String(length=10), server_default='MÉDIA', nullable=False),
    sa.Column('status', sa.String(length=10), server_default='ABERTA', nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['tb_usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cfg_pendencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cfg_pendencias_cr_norm'), ['cr_norm'], unique=False)

    op.create_table('cfg_pleitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cr_norm', sa.String(length=40), nullable=False),
    sa.Column('data_base', sa.Date(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=15), server_default='ADITIVO', nullable=False),
    sa.Column('status', sa.String(length=15), server_default='SOLICITAR', nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_por_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['tb_usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cfg_pleitos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cfg_pleitos_cr_norm'), ['cr_norm'], unique=False)

    op.create_table('sync_execucoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disparo', sa.String(length=15), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('terminado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=15), server_default='em_andamento', nullable=False),
    sa.Column('contagens', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('alvo_tipo', sa.String(length=50), nullable=False),
    sa.Column('alvo_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tb_usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_auditoria_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_auditoria_alvo_id'), ['alvo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_auditoria_alvo_tipo'), ['alvo_tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_auditoria_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_auditoria_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_auditoria_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_tb_auditoria_criado_em'))
        batch_op.drop_index(batch_op.f('ix_tb_auditoria_alvo_tipo'))
        batch_op.drop_index(batch_op.f('ix_tb_auditoria_alvo_id'))
        batch_op.drop_index(batch_op.f('ix_tb_auditoria_acao'))

    op.drop_table('tb_auditoria')
    op.drop_table('sync_execucoes')
    with op.batch_alter_table('cfg_pleitos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cfg_pleitos_cr_norm'))

    op.drop_table('cfg_pleitos')
    with op.batch_alter_table('cfg_pendencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cfg_pendencias_cr_norm'))

    op.drop_table('cfg_pendencias')
    op.drop_table('cfg_parametros')
    with op.batch_alter_table('cfg_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cfg_itens_cr_norm'))

    op.drop_table('cfg_itens')
    op.drop_table('cfg_importacoes')
    with op.batch_alter_table('cfg_depara', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cfg_depara_cr_norm'))

    op.drop_table('cfg_depara')
    op.drop_table('cfg_contratos')
    with op.batch_alter_table('cfg_bms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cfg_bms_cr_norm'))

    op.drop_table('cfg_bms')
    with op.batch_alter_table('tb_usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_usuarios_external_id'))
        batch_op.drop_index(batch_op.f('ix_tb_usuarios_email'))

    op.drop_table('tb_usuarios')
    op.drop_table('sync_marcas')
    with op.batch_alter_table('rc_recebimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rc_recebimentos_nf_origem_id'))

    op.drop_table('rc_recebimentos')
    with op.batch_alter_table('rc_previsoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rc_previsoes_contrato_origem_id'))

    op.drop_table('rc_previsoes')
    with op.batch_alter_table('rc_nfs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rc_nfs_emitida_em'))
        batch_op.drop_index(batch_op.f('ix_rc_nfs_contrato_origem_id'))

    op.drop_table('rc_nfs')
    with op.batch_alter_table('rc_contratos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rc_contratos_cr_norm'))
        batch_op.drop_index(batch_op.f('ix_rc_contratos_cliente_origem_id'))

    op.drop_table('rc_contratos')
    with op.batch_alter_table('rc_contrato_coordenadores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rc_contrato_coordenadores_nome_norm'))
        batch_op.drop_index(batch_op.f('ix_rc_contrato_coordenadores_contrato_origem_id'))

    op.drop_table('rc_contrato_coordenadores')
    op.drop_table('rc_clientes')
    with op.batch_alter_table('rc_ajustes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rc_ajustes_contrato_origem_id'))

    op.drop_table('rc_ajustes')
    with op.batch_alter_table('cd_naturezas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cd_naturezas_nome_norm'))

    op.drop_table('cd_naturezas')
    op.drop_table('cd_fornecedores')
    with op.batch_alter_table('cd_despesas', schema=None) as batch_op:
        batch_op.drop_index('ix_cd_despesas_centro_natureza_data')
        batch_op.drop_index('ix_cd_despesas_centro_data')

    op.drop_table('cd_despesas')
    with op.batch_alter_table('cd_centros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cd_centros_cr_norm'))

    op.drop_table('cd_centros')
    # ### end Alembic commands ###
